name: binding_free_energy
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=2.136=openblas
  - blas-devel=3.9.0=36_h1ea3ea9_openblas
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=hf7d4471_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.12.0=h80c7b02_0
  - ca-certificates=2025.9.9=h06a4308_0
  - click=8.3.0=pyh707e725_0
  - cudatoolkit=10.2.89=h713d32c_10
  - expat=2.7.1=h6a678d5_0
  - flask=3.1.2=pyhd8ed1ab_0
  - hdf5=1.14.5=h2b7332f_2
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - krb5=1.21.3=h723845a_4
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libcblas=3.9.0=36_h0358290_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgomp=15.1.0=h767d61c_5
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=36_h47877c9_openblas
  - liblapacke=3.9.0=36_h6ae95b6_openblas
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=h46f56fc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=2.1.1=py310h5764c6d_1
  - mdtraj=1.10.3=py310h4cdbd58_0
  - ncurses=6.5=h7934f7d_0
  - nomkl=3.0=0
  - numexpr=2.8.0=py310hf05e7a9_102
  - numpy=1.26.4=py310hc213724_1
  - numpy-base=1.26.4=py310hf387b04_1
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - openmm=8.0.0=py310h466fd29_1
  - openmm-setup=1.4=pyhca7485f_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310h5eaa309_1
  - pdbfixer=1.9=pyh1a96a4e_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pymbar=3.0.7=py310hde88566_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pytables=3.10.1=py310h759fa19_1
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.3=hc2a1206_0
  - scipy=1.12.0=py310heeff2f4_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - intspan==1.6.1
      - openbabel-wheel==3.1.1.22
prefix: /iahome/a/an/andthiel/Programs/miniconda3/envs/binding_free_energy
