name: binding_free_energy
channels:
  - defaults
dependencies:
  - python=3.9
  - cuda-version=12.2
  - conda-forge::openmm==8.1.2
  - conda-forge::pymbar[version'>3']
  - conda-forge::pdbfixer
  - conda-forge::mdtraj
  - conda-forge::openjdk=21
  - conda-forge::openbabel
  - pip:
    - intspan==1.6.1
